### ISSUE TITLE
Test suite doesn't build on darwin

### ISSUE THREAD

**Issue by sternenseemann** [typeclasses/assoc-list#2]
Due to the case insensitive nature of darwin's file system GHC will complain that it can't distinguish between `hedgehog.hs` which is supposedly a `Main` module and the `Hedgehog` module in scope, resulting in the following, quite confusing error:

```
test/Hedgehog.hs:1:1: error:
    File name does not match module name:
    Saw: ‘Main’
    Expected: ‘Hedgehog’
```

Renaming the test entrypoint to `Main.hs` or similar should fix this.

This affects assoc-list and assoc-listlike.

**Comment by chris-martin** [comment]
Fixed in:

  - https://hackage.haskell.org/package/assoc-list-0.1.0.1
  - https://hackage.haskell.org/package/assoc-listlike-0.1.0.1
